### PR TITLE
Fixing basic NPM install errors

### PR DESCRIPTION
**Pull request by simonwex**
```
(develop) ~/projects/togetherjs$ npm install
WARN tarball tarball data for esprima@https://github.com/ariya/esprima/tarball/master (sha1-C0XMQgDkwwAPPkY1H9aa+FeCIPo=) seems to be corrupted. Trying one more time.
WARN tarball tarball data for esprima@https://github.com/ariya/esprima/tarball/master (sha1-C0XMQgDkwwAPPkY1H9aa+FeCIPo=) seems to be corrupted. Trying one more time.
npm WARN togetherjs@0.4.0-a No license field.
npm WARN The package optimist is included as both a dev and production dependency.

npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting esprima@https://github.com/ariya/esprima/tarball/master:
npm ERR! Verification failed while extracting esprima@https://github.com/ariya/esprima/tarball/master:
npm ERR! sha1-C0XMQgDkwwAPPkY1H9aa+FeCIPo= integrity checksum failed when using sha1: wanted sha1-C0XMQgDkwwAPPkY1H9aa+FeCIPo= but got sha512-NpIIa83N47pO8m01O9ja94K9aaU8suEP+Z5w+cFzahlrCDw+dESpBpfwrqJI0RFDaAW+gJYsxZSc4T/amhR56Q== sha1-E/C3R8GnSdYHW4N7ZIxCtBs1zkQ=. (6402210 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simon/.npm/_logs/2019-01-31T23_59_55_673Z-debug.log
```

Fixing the above error. Not all tests passing, but consistent with what is passing on develop.

### CODE REVIEW

**Comment by simonwex** [comment]
@Pomax how do you feel about firing this old project up on your machine?

**Comment by Pomax** [comment]
I can give it a shot, anything in particular you want me to run?

**Comment by Pomax** [comment]
Looks like I'm getting stuck during `npm test`, but that feels a little farther than you got?

```
c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs>git checkout back-to-basics
Switched to a new branch 'back-to-basics'
Branch 'back-to-basics' set up to track remote branch 'back-to-basics' from 'origin'.

c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs>
c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs>npm i
npm WARN notice [SECURITY] cookie-signature has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=cookie-signature&version=0.0.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] express has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=express&version=3.0.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] ecstatic has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=ecstatic&version=0.4.13 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] concat-stream has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=concat-stream&version=1.5.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] connect has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=connect&version=2.7.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] send has the following vulnerabilities: 2 low. Go here for more details: https://nodesecurity.io/advisories?search=send&version=0.1.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] qs has the following vulnerabilities: 2 high. Go here for more details: https://nodesecurity.io/advisories?search=qs&version=0.5.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] mime has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=mime&version=1.2.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] fresh has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=fresh&version=0.1.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> phantomjs@1.9.20 install c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-windows.zip
Saving to C:\Users\Mike\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...
  [======================================--] 94%
Received 7292K total.
Extracting zip contents
Removing J:\Junctions\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\Mike\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1548980559831\phantomjs-1.9.8-windows -> J:\Junctions\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at J:\Junctions\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\phantomjs\lib\phantom\phantomjs.exe

> websocket@1.0.28 install c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Users\Mike\AppData\Roaming\nvm\v8.11.4\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Mike\AppData\Roaming\nvm\v8.11.4\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
  win_delay_load_hook.cc
     Creating library c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\websocket\build\Release\bufferutil.lib and object c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs
  \node_modules\websocket\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\websocket\build\Release\\bufferutil.node
  bufferutil.vcxproj -> c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\websocket\build\Release\bufferutil.pdb (Full PDB)
  validation.cc
  win_delay_load_hook.cc
     Creating library c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\websocket\build\Release\validation.lib and object c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs
  \node_modules\websocket\build\Release\validation.exp
  Generating code
  Finished generating code
  validation.vcxproj -> c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\websocket\build\Release\\validation.node
  validation.vcxproj -> c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs\node_modules\websocket\build\Release\validation.pdb (Full PDB)
npm WARN togetherjs@0.4.0-a No license field.
npm WARN The package optimist is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 403 packages in 38.834s

c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs>npm test

> togetherjs@0.4.0-a test c:\Users\Mike\Documents\Git\collaborations\mozilla\togetherjs
> grunt test

Running "jshint:all" (jshint) task
>> 31 files lint free.

Running "phantom-setup" task

Running "copylib" task
Copying files from togetherjs/ to test-build\togetherjs

Running "maybeless" task

Running "less:development" (less) task
File test-build/togetherjs/togetherjs.css created.
File test-build/togetherjs/recorder.css created.

Running "substitute" task
Using hub URL http://localhost:65297
writing togetherjs/togetherjs.js to test-build/togetherjs.js
writing togetherjs/togetherjs.js to test-build/togetherjs-min.js
writing test-build\togetherjs\templates-en-US.js based on togetherjs/locale/en-US.json
writing test-build\togetherjs\templates-es-BO.js based on togetherjs/locale/es-BO.json
writing test-build\togetherjs\templates-pl-PL.js based on togetherjs/locale/pl-PL.json
writing test-build\togetherjs\templates-ru.js based on togetherjs/locale/ru.json

Running "config-requirejs" task

Running "requirejs:compile" (requirejs) task

Running "http-server:test" (http-server) task
Server running on  localhost:65298
Hit CTRL-C to stop the server

Running "phantom-tests:test_console.js" (phantom-tests) task
(node:13784) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> 2 assertions passed (4097ms)

Running "phantom-tests:test_elementFinder.js" (phantom-tests) task
(node:13784) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> 2 assertions passed (2123ms)

Running "phantom-tests:test_linkify.js" (phantom-tests) task
(node:13784) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> 4 assertions passed (1826ms)

Running "phantom-tests:test_misc.js" (phantom-tests) task
(node:13784) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> 8 assertions passed (2027ms)

Running "phantom-tests:test_ot_text.js" (phantom-tests) task
```
(and then it looks like it's stalled)

**Comment by simonwex** [comment]
Yeah, perhaps this is a good enough to continue on branch for "back-to-basics". Let's leave this PR open and I'll see if I can get all the tests passing.

**Comment by Pomax** [comment]
In an effort to bring my "open issues I'm mentioned in" list back to manageable size: does it still make sense to leave this open, or does it make more sense to close it and just work on that alternate branch without a PR instead?

**Comment by Pomax** [comment]
closing as very out of date

**Comment by Pomax** [comment]
It looks like this PR never _actually_ got closed, but it should be. Can one of the new project owners close this one out? Or @simonwex of course =)

**Comment by Pomax** [comment]
@simonwex would it be possible to close this PR? There's no way for me to take it out of my github mentions, and the odds of this PR ever landing are effectively zero at this point in time =)

**Comment by simonwex** [comment]
@Pomax 👍 !

(Also, 👋 )

**Comment by Pomax** [comment]
Thanks! (and sorry!) (and also 👋 back!)

**Pull request closed without merging**
